### ISSUE TITLE
Перевозка домашних животных. Птицы

### ISSUE THREAD

**Issue by Hexronimo** [ITTalentEstonia/guide_ee_ru#35]
Есть информация, полученная от Ветеринарно-Продовольственного Департамента Эстонии в марте 2019 года относительно перевозки попугая. Можно дополнить раздел про pet'ов, так как на данный момент он только про млекопитающих (прививка от бешенства птицам, понятное дело, не нужна) или просто дать там ссылку на эту страницу.
Вопрос был задан именно потому что информация на сайте и в законе по поводу птиц очень расплывчата.

> Добрый день!
> Если вы планируете приехать с попугаем  (для некоммерческих целей) в Эстонию, вам необходимо будет выполнить следующие требования:
> Решение Эвро Комиссии 2007/25 (с поправками, внесенными Решением 2018/1687)  вводит гарантии для высокопатогенного птичьего гриппа и перемещения птиц, сопровождающих их владельцев, в Эвро Союз.
> С  птицей должен сопровождаться оригинальный **ветеринарный сертификат (приложен), выданным официальным ветеринарным врачом третьей страны отправки (Россия) с декларацией владельца (приложена), которая должна быть заполнена владельцем птицы непосредственно после получения сертификата** **(прим. это ответ на вопрос о декларации владельца, т.к. изначально документов на птицу нет)**.
> **Птицы должны быть помечены.** **(прим. это ответ о чипировании. И из него ничего не ясно :( )**
> Кроме того, должно быть выполнено **одно** из следующих условий:
> (а) птица находилась в предварительном карантине за 30 дней до отправления, указанного в Части 1 Приложения I к Регламенту (ЕС) № 206/2010 или Части 1 Приложения II (Россия включена в Приложения);
> (b) птица  подвергается 30-дневному карантинному учреждению в утвержденном центре по карантину птиц (Постановление 139/2013, ст. 6) после ввоза; (прим. это, видимо,  для сельхоз птиц)
> (c) птица была вакцинирована  вакциной против вирусов птичьего гриппа подтипов H5 и H7 в течение не менее 6 месяца и ревакцинирована не позже чем за 60 дней до даты выезда;
>** (d) птица была изолирована в течение по крайней мере 10 дней до вывоза из страны, и в течение этого периода были взяты пробы для изучения наличия антигенов или геномов подтипов H5 и H7.** **(на первый взгляд это самый простой и нестреcсовый вариант)**
> Образцы не должны быть взяты ранее, чем на третий день изоляции - **квартирное содержание без других птиц считается изоляцией;**
> 
> Все проведенные исследования и прививки должны быть отмечены в сертификате.
> CITES сертификат не нужен **(прим. вопрос был по корелле - для корелл и волнистых не нужен, для остальных нужен)**

Таким образом, на мой взгляд, самый простой вариант: получить сертификат и декларацию за неделю до вывоза и сразу туда вписать результаты анализа по гриппу. Но вот как "пометить" птицу все еще не понятно - на птичьем форуме мне тоже не ответили, сказали что чипирования для маленьких птиц скорее всего не бывает.

Если кому-то надо могу переслать письмо, там еще есть контакты и имя сотрудника.
Прикреплены образцы сертификата и декларации, которые приложил к письму сотрудник.

[lemmiklinnud sert.docx](https://github.com/ITTalentEstonia/guide_ee_ru/files/3908085/lemmiklinnud.sert.docx)
[Lemmiklinnu omanikuvõi esindaja deklaratsioon.docx](https://github.com/ITTalentEstonia/guide_ee_ru/files/3908059/Lemmiklinnu.omanikuvoi.esindaja.deklaratsioon.docx)

**Comment by swith** [comment]
Можете PR сделать? Я проверю, аппрувну

**Comment by Hexronimo** [comment]
Сделаю в четверг или чуть позже.

**Comment by Hexronimo** [comment]
Готово
